# Generated by Django 3.0.4 on 2020-03-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200325_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='', verbose_name='Фотография профиля'),
        ),
    ]
